language: rust
rust:
  - 1.11.0

before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq build-essential pkg-config
    - sudo apt-get install -qq python-dev libboost-python-dev
    - sudo apt-get install -qq coinor-libosi-dev coinor-libcoinutils-dev coinor-libclp-dev libbz2-dev
