language: rust
rust:
  - 1.11.0
  - 1.13.0
  - 1.16.0
  - 1.17.0
  - 1.20.0

before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq coinor-cbc
